//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace Ris.Client.Messages.Request {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    [System.Xml.Serialization.XmlRootAttribute("OGDSearchRequest", Namespace="http://ris.bka.gv.at/Search/1.3/OGD", IsNullable=false)]
    public partial class T_OGDSearchRequest {
        
        private SearchExpression suchworteField;
        
        private SearchExpression titelField;
        
        private SearchExpression indexField;
        
        private NormabschnittSucheinschraenkung abschnittField;
        
        private System.DateTime fassungVomField;
        
        private bool fassungVomFieldSpecified;
        
        private PhraseSearchExpression kundmachungsorganField;
        
        private PhraseSearchExpression kundmachungsorgannummerField;
        
        private ChangeSetInterval imRisSeitField;
        
        private bool imRisSeitFieldSpecified;
        
        private PageSize dokumenteProSeiteField;
        
        private bool dokumenteProSeiteFieldSpecified;
        
        private int seitennummerField;
        
        private BundesnormenSortExpression sortierungField;
        
        /// <remarks/>
        public SearchExpression Suchworte {
            get {
                return this.suchworteField;
            }
            set {
                this.suchworteField = value;
            }
        }
        
        /// <remarks/>
        public SearchExpression Titel {
            get {
                return this.titelField;
            }
            set {
                this.titelField = value;
            }
        }
        
        /// <remarks/>
        public SearchExpression Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        public NormabschnittSucheinschraenkung Abschnitt {
            get {
                return this.abschnittField;
            }
            set {
                this.abschnittField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FassungVom {
            get {
                return this.fassungVomField;
            }
            set {
                this.fassungVomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FassungVomSpecified {
            get {
                return this.fassungVomFieldSpecified;
            }
            set {
                this.fassungVomFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PhraseSearchExpression Kundmachungsorgan {
            get {
                return this.kundmachungsorganField;
            }
            set {
                this.kundmachungsorganField = value;
            }
        }
        
        /// <remarks/>
        public PhraseSearchExpression Kundmachungsorgannummer {
            get {
                return this.kundmachungsorgannummerField;
            }
            set {
                this.kundmachungsorgannummerField = value;
            }
        }
        
        /// <remarks/>
        public ChangeSetInterval ImRisSeit {
            get {
                return this.imRisSeitField;
            }
            set {
                this.imRisSeitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImRisSeitSpecified {
            get {
                return this.imRisSeitFieldSpecified;
            }
            set {
                this.imRisSeitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PageSize DokumenteProSeite {
            get {
                return this.dokumenteProSeiteField;
            }
            set {
                this.dokumenteProSeiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DokumenteProSeiteSpecified {
            get {
                return this.dokumenteProSeiteFieldSpecified;
            }
            set {
                this.dokumenteProSeiteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Seitennummer {
            get {
                return this.seitennummerField;
            }
            set {
                this.seitennummerField = value;
            }
        }
        
        /// <remarks/>
        public BundesnormenSortExpression Sortierung {
            get {
                return this.sortierungField;
            }
            set {
                this.sortierungField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanSearchExpression))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AndSearchExpression))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrSearchExpression))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TermSearchExpression))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NotSearchExpression))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhraseSearchExpression))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public abstract partial class SearchExpression {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public partial class BundesnormenSortExpression {
        
        private WebSortDirection sortDirectionField;
        
        private BundesnormenSortableColumn sortedByColumnField;
        
        /// <remarks/>
        public WebSortDirection SortDirection {
            get {
                return this.sortDirectionField;
            }
            set {
                this.sortDirectionField = value;
            }
        }
        
        /// <remarks/>
        public BundesnormenSortableColumn SortedByColumn {
            get {
                return this.sortedByColumnField;
            }
            set {
                this.sortedByColumnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public enum WebSortDirection {
        
        /// <remarks/>
        Ascending,
        
        /// <remarks/>
        Descending,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public enum BundesnormenSortableColumn {
        
        /// <remarks/>
        ArtikelParagraphAnlage,
        
        /// <remarks/>
        Kurzinformation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public partial class NormabschnittSucheinschraenkung {
        
        private string nummerVonField;
        
        private string buchstabeVonField;
        
        private int nummerBisField;
        
        private bool nummerBisFieldSpecified;
        
        private string buchstabeBisField;
        
        private NormabschnittTyp typField;
        
        private bool typFieldSpecified;
        
        /// <remarks/>
        public string NummerVon {
            get {
                return this.nummerVonField;
            }
            set {
                this.nummerVonField = value;
            }
        }
        
        /// <remarks/>
        public string BuchstabeVon {
            get {
                return this.buchstabeVonField;
            }
            set {
                this.buchstabeVonField = value;
            }
        }
        
        /// <remarks/>
        public int NummerBis {
            get {
                return this.nummerBisField;
            }
            set {
                this.nummerBisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NummerBisSpecified {
            get {
                return this.nummerBisFieldSpecified;
            }
            set {
                this.nummerBisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string BuchstabeBis {
            get {
                return this.buchstabeBisField;
            }
            set {
                this.buchstabeBisField = value;
            }
        }
        
        /// <remarks/>
        public NormabschnittTyp Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypSpecified {
            get {
                return this.typFieldSpecified;
            }
            set {
                this.typFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public enum NormabschnittTyp {
        
        /// <remarks/>
        Alle,
        
        /// <remarks/>
        Artikel,
        
        /// <remarks/>
        Paragraph,
        
        /// <remarks/>
        Anlage,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AndSearchExpression))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrSearchExpression))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public abstract partial class BooleanSearchExpression : SearchExpression {
        
        private SearchExpression[] expressionsField;
        
        /// <remarks/>
        public SearchExpression[] Expressions {
            get {
                return this.expressionsField;
            }
            set {
                this.expressionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public partial class AndSearchExpression : BooleanSearchExpression {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public partial class OrSearchExpression : BooleanSearchExpression {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public partial class TermSearchExpression : SearchExpression {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public partial class NotSearchExpression : SearchExpression {
        
        private SearchExpression expressionField;
        
        /// <remarks/>
        public SearchExpression Expression {
            get {
                return this.expressionField;
            }
            set {
                this.expressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public partial class PhraseSearchExpression : SearchExpression {
        
        private string valueField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public enum ChangeSetInterval {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        EinerWoche,
        
        /// <remarks/>
        ZweiWochen,
        
        /// <remarks/>
        EinemMonat,
        
        /// <remarks/>
        DreiMonaten,
        
        /// <remarks/>
        SechsMonaten,
        
        /// <remarks/>
        EinemJahr,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ris.bka.gv.at/Search/1.3/OGD")]
    public enum PageSize {
        
        /// <remarks/>
        Ten,
        
        /// <remarks/>
        Twenty,
        
        /// <remarks/>
        Fifty,
        
        /// <remarks/>
        OneHundred,
    }
}
