//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace Ris.Client
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://ogd.bka.gv.at/", ConfigurationName = "RISServices.OGDServiceSoap")]
    public interface OGDServiceSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://ogd.bka.gv.at/request", ReplyAction = "*")]
        System.Threading.Tasks.Task<Ris.Client.requestResponse> requestAsync(Ris.Client.requestRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ogd.bka.gv.at/getDocument", ReplyAction = "*")]
        System.Threading.Tasks.Task<Ris.Client.getDocumentResponse> getDocumentAsync(Ris.Client.getDocumentRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://ogd.bka.gv.at/version", ReplyAction = "*")]
        System.Threading.Tasks.Task<Ris.Client.versionResponse> versionAsync(Ris.Client.versionRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class requestRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "request", Namespace = "http://ogd.bka.gv.at/", Order = 0)]
        public Ris.Client.requestRequestBody Body;

        public requestRequest()
        {
        }

        public requestRequest(Ris.Client.requestRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ogd.bka.gv.at/")]
    public partial class requestRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string application;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string query;

        public requestRequestBody()
        {
        }

        public requestRequestBody(string application, string query)
        {
            this.application = application;
            this.query = query;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class requestResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "requestResponse", Namespace = "http://ogd.bka.gv.at/", Order = 0)]
        public Ris.Client.requestResponseBody Body;

        public requestResponse()
        {
        }

        public requestResponse(Ris.Client.requestResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ogd.bka.gv.at/")]
    public partial class requestResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string requestResult;

        public requestResponseBody()
        {
        }

        public requestResponseBody(string requestResult)
        {
            this.requestResult = requestResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class getDocumentRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "getDocument", Namespace = "http://ogd.bka.gv.at/", Order = 0)]
        public Ris.Client.getDocumentRequestBody Body;

        public getDocumentRequest()
        {
        }

        public getDocumentRequest(Ris.Client.getDocumentRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ogd.bka.gv.at/")]
    public partial class getDocumentRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string application;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string docId;

        public getDocumentRequestBody()
        {
        }

        public getDocumentRequestBody(string application, string docId)
        {
            this.application = application;
            this.docId = docId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class getDocumentResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "getDocumentResponse", Namespace = "http://ogd.bka.gv.at/", Order = 0)]
        public Ris.Client.getDocumentResponseBody Body;

        public getDocumentResponse()
        {
        }

        public getDocumentResponse(Ris.Client.getDocumentResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ogd.bka.gv.at/")]
    public partial class getDocumentResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string getDocumentResult;

        public getDocumentResponseBody()
        {
        }

        public getDocumentResponseBody(string getDocumentResult)
        {
            this.getDocumentResult = getDocumentResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class versionRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "version", Namespace = "http://ogd.bka.gv.at/", Order = 0)]
        public Ris.Client.versionRequestBody Body;

        public versionRequest()
        {
        }

        public versionRequest(Ris.Client.versionRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class versionRequestBody
    {

        public versionRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class versionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "versionResponse", Namespace = "http://ogd.bka.gv.at/", Order = 0)]
        public Ris.Client.versionResponseBody Body;

        public versionResponse()
        {
        }

        public versionResponse(Ris.Client.versionResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://ogd.bka.gv.at/")]
    public partial class versionResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string versionResult;

        public versionResponseBody()
        {
        }

        public versionResponseBody(string versionResult)
        {
            this.versionResult = versionResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OGDServiceSoapChannel : Ris.Client.OGDServiceSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OGDServiceSoapClient : System.ServiceModel.ClientBase<Ris.Client.OGDServiceSoap>, Ris.Client.OGDServiceSoap
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public OGDServiceSoapClient() :
            base(OGDServiceSoapClient.GetDefaultBinding(), OGDServiceSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OGDServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OGDServiceSoapClient(EndpointConfiguration endpointConfiguration) :
            base(OGDServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), OGDServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OGDServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
            base(OGDServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OGDServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
            base(OGDServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OGDServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ris.Client.requestResponse> Ris.Client.OGDServiceSoap.requestAsync(Ris.Client.requestRequest request)
        {
            return base.Channel.requestAsync(request);
        }

        public System.Threading.Tasks.Task<Ris.Client.requestResponse> requestAsync(string application, string query)
        {
            Ris.Client.requestRequest inValue = new Ris.Client.requestRequest();
            inValue.Body = new Ris.Client.requestRequestBody();
            inValue.Body.application = application;
            inValue.Body.query = query;
            return ((Ris.Client.OGDServiceSoap)(this)).requestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ris.Client.getDocumentResponse> Ris.Client.OGDServiceSoap.getDocumentAsync(Ris.Client.getDocumentRequest request)
        {
            return base.Channel.getDocumentAsync(request);
        }

        public System.Threading.Tasks.Task<Ris.Client.getDocumentResponse> getDocumentAsync(string application, string docId)
        {
            Ris.Client.getDocumentRequest inValue = new Ris.Client.getDocumentRequest();
            inValue.Body = new Ris.Client.getDocumentRequestBody();
            inValue.Body.application = application;
            inValue.Body.docId = docId;
            return ((Ris.Client.OGDServiceSoap)(this)).getDocumentAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ris.Client.versionResponse> Ris.Client.OGDServiceSoap.versionAsync(Ris.Client.versionRequest request)
        {
            return base.Channel.versionAsync(request);
        }

        public System.Threading.Tasks.Task<Ris.Client.versionResponse> versionAsync()
        {
            Ris.Client.versionRequest inValue = new Ris.Client.versionRequest();
            inValue.Body = new Ris.Client.versionRequestBody();
            return ((Ris.Client.OGDServiceSoap)(this)).versionAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OGDServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OGDServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://data.bka.gv.at/RIS/OGDService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OGDServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.OGDServiceSoap);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OGDServiceSoapClient.GetEndpointAddress(EndpointConfiguration.OGDServiceSoap);
        }

        public enum EndpointConfiguration
        {

            OGDServiceSoap,
        }
    }
}
